### ISSUE TITLE
Reorder tab title text

### ISSUE THREAD

**Issue by polakowski** [Selleo/DevPath#184]
### Problem
When I have multiple tabs opened, it's hard to see what's opened in the tab.

### Current behavior
All tabs read "Selleo DevPath Framework..."

### Expected behavior
Tabs should specify opened technology at the beginning, e.g. "PWA - Selleo DevPath...", "React/Advanced - Selleo DevPath..." 

![image](https://user-images.githubusercontent.com/9076315/184490984-27abab0b-010d-4761-803b-37a90d8a619c.png)

**Comment by qbart** [comment]
simple yet needed, fixed in https://github.com/Selleo/DevPath/commit/7e09f94cb714e7016d55c15c6e609c312270ce58
