### ISSUE TITLE
QA junior abilities suggestion

### ISSUE THREAD

**Issue by BobrImperator** [Selleo/DevPath#54]
### CSS Selectors

QA should know css selectors https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors
When testing frontend it's inevitable for a QA person to work with HTML because there's always a need to validate some element value or perform a click.

QA should be able to write concise and preferably tag agnostic selectors or modify them instead of relying on recording tools e.g endtest.

example:
In a test we want to see if clicking on an element redirects us to a specific route.

a recording tool generates an xPath like this:
```
ul[data-test-group="store_links"] > li:nth-of-type(3) > a[data-test-link="nav-link-taxes"]>div>span
```
QA should be able to tweak the selector so it looks like this:

```
[data-test-group="store_links"] [data-test-link="nav-link-taxes"]
```

### Browser networking

QA should be able to report issues using network, requests info.
Use network throttling.

**Comment by PoslinskiNet** [comment]
@maciejhubert do you think it should be the responsibility of the Junior QA?

**Comment by maciejhubert** [comment]
@BobrImperator CSS Selectors are more fit to be in Independent/Mid in devPath (test scripts are planned to be more or less in Mid). You can see a high level description of QA levels [here](https://connect.zoho.eu/portal/intranet/forum/post/qa-engineer). As for now devPath exists only for [junior](https://selleo.com/devpath/qa/01_junior_i/).

Although, as in Greenbits project it is required for QA to have some knowledge of automation and CSS selectors, Tomek is learning them parallelly regardless what the devPath contains.

Throttling is a good idea and I will add it to junior's skills.
