### ISSUE TITLE
Content search issues

### ISSUE THREAD

**Issue by Zealur** [Selleo/DevPath#66]
![image](https://user-images.githubusercontent.com/11999967/101992175-92850080-3cb1-11eb-8cb3-4ccf4879ecc3.png)

- Chevrons are in separate lines from text
- Some rows have no text at all

**Comment by PoslinskiNet** [comment]
@Zealur once we will close https://github.com/Selleo/DevPath/issues/82 we will focus on this one. Actually, it is more about adding proper meta keywords in files so it fills the gaps (some files already have this).

**Comment by qbart** [comment]
I checked all content files, added missing metadata.
