### ISSUE TITLE
Link for resource in "Common > MacOS" is dead

### ISSUE THREAD

**Issue by Zealur** [Selleo/DevPath#67]
https://selleo.com/devpath/common/macos/
Common > MacOS > `setup your mac for development and learn about apps` link is dead
![image](https://user-images.githubusercontent.com/11999967/102465082-83090d00-404d-11eb-8cd5-fb1f6fe69ad9.png)

**Comment by PoslinskiNet** [comment]
It was merged to web dev fundamentals - the rest of the OS-related materials are staying in Linux now.
